spring.application.name=content-search
spring.datasource.url=jdbc:postgresql://localhost:5432/content_search_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
